name: Run tests
run-name: Release beancount-cc-importer to PyPI
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: pdm-project/setup-pdm@v3

    - name: Install dependencies
      run: pdm install --no-lock

    - name: Run test
      run: pdm run pytest